version: '3.9'

networks:
  vr-pharmacy-server-network:
    name: vr-pharmacy-server-network
    driver: bridge

volumes:
  vr-pharmacy-server-database-volume:

services:
  api:
    build:
      context: .
      dockerfile: docker/image/Dockerfile
      args:
        ENV: lite
    container_name: vr-pharmacy-server-api
    restart: always
    command: ["/app/docker/entrypoint/api.sh"]
    ports: ["8001:80"]
    environment:
      PHP_POOL_NAME: "vr-pharmacy-server-api"
    volumes:
      - vr-pharmacy-server-database-volume:/db
    networks:
      - vr-pharmacy-server-network
