version: '3.9'

networks:
  my-awesome-project-network:
    name: my-awesome-project-network
    driver: bridge
  my-awesome-project-databases-network:
    name: my-awesome-project-databases-network
    driver: bridge

volumes:
  my-awesome-project-redis-volume:
  my-awesome-project-postgres-database-volume:
  my-awesome-project-postgres-home-volume:

services:
  api:
    build:
      context: .
      dockerfile: docker/image/Dockerfile
      args:
        ENV: containerized
    container_name: my-awesome-project-api
    restart: always
    command: ["/app/docker/entrypoint/api.sh"]
    ports: ["8000:80"]
    environment:
      PHP_POOL_NAME: "my-awesome-project-api"
    networks:
      - my-awesome-project-network
      - my-awesome-project-databases-network
    depends_on:
      - redis
      - postgres

  task:
    build:
      context: .
      dockerfile: docker/image/Dockerfile
      args:
        ENV: containerized
    container_name: my-awesome-project-task
    restart: always
    command: ["/app/docker/entrypoint/task.sh"]
    environment:
      PHP_POOL_NAME: "my-awesome-project-task"
    networks:
      - my-awesome-project-network
      - my-awesome-project-databases-network
    depends_on:
      - redis
      - postgres

  queue:
    build:
      context: .
      dockerfile: docker/image/Dockerfile
      args:
        ENV: containerized
    container_name: my-awesome-project-queue
    restart: always
    command: ["/app/docker/entrypoint/queue.sh"]
    environment:
      PHP_POOL_NAME: "my-awesome-project-queue"
    networks:
      - my-awesome-project-network
      - my-awesome-project-databases-network
    depends_on:
      - redis
      - postgres

  redis:
    image: redislabs/rejson:2.2.0
    container_name: my-awesome-project-redis
    restart: always
    ports: ["6379:6379"]
    volumes:
      - my-awesome-project-redis-volume:/data
    networks:
      - my-awesome-project-databases-network

  postgres:
    image: postgres:14.5-alpine
    container_name: my-awesome-project-postgres
    restart: always
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: my-awesome-project
      POSTGRES_USER: my-awesome-project
      POSTGRES_PASSWORD: my-awesome-project
    volumes:
      - my-awesome-project-postgres-database-volume:/var/lib/postgresql/data
      - my-awesome-project-postgres-home-volume:/root
    networks:
      - my-awesome-project-databases-network
