version: '3.9'

networks:
  vr-pharmacy-server-network:
    name: vr-pharmacy-server-network
    driver: bridge
  vr-pharmacy-server-databases-network:
    name: vr-pharmacy-server-databases-network
    driver: bridge

volumes:
  vr-pharmacy-server-redis-volume:
  vr-pharmacy-server-postgres-database-volume:
  vr-pharmacy-server-postgres-home-volume:

services:
  api:
    build:
      context: .
      dockerfile: docker/image/Dockerfile
      args:
        ENV: containerized
    container_name: vr-pharmacy-server-api
    restart: always
    command: ["/app/docker/entrypoint/api.sh"]
    ports: ["8001:80"]
    environment:
      PHP_POOL_NAME: "vr-pharmacy-server-api"
    networks:
      - vr-pharmacy-server-network
      - vr-pharmacy-server-databases-network
    depends_on:
      - redis
      - postgres

  task:
    build:
      context: .
      dockerfile: docker/image/Dockerfile
      args:
        ENV: containerized
    container_name: vr-pharmacy-server-task
    restart: always
    command: ["/app/docker/entrypoint/task.sh"]
    environment:
      PHP_POOL_NAME: "vr-pharmacy-server-task"
    networks:
      - vr-pharmacy-server-network
      - vr-pharmacy-server-databases-network
    depends_on:
      - redis
      - postgres

  queue:
    build:
      context: .
      dockerfile: docker/image/Dockerfile
      args:
        ENV: containerized
    container_name: vr-pharmacy-server-queue
    restart: always
    command: ["/app/docker/entrypoint/queue.sh"]
    environment:
      PHP_POOL_NAME: "vr-pharmacy-server-queue"
    networks:
      - vr-pharmacy-server-network
      - vr-pharmacy-server-databases-network
    depends_on:
      - redis
      - postgres

  redis:
    image: redislabs/rejson:2.2.0
    container_name: vr-pharmacy-server-redis
    restart: always
    ports: ["6379:6379"]
    volumes:
      - vr-pharmacy-server-redis-volume:/data
    networks:
      - vr-pharmacy-server-databases-network

  postgres:
    image: postgres:14.5-alpine
    container_name: vr-pharmacy-server-postgres
    restart: always
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: vr-pharmacy-server
      POSTGRES_USER: vr-pharmacy-server
      POSTGRES_PASSWORD: vr-pharmacy-server
    volumes:
      - vr-pharmacy-server-postgres-database-volume:/var/lib/postgresql/data
      - vr-pharmacy-server-postgres-home-volume:/root
    networks:
      - vr-pharmacy-server-databases-network
