version: '3.9'

networks:
  vr-pharmacy-server-databases-network:
    name: vr-pharmacy-server-databases-network
    driver: bridge

volumes:
  vr-pharmacy-server-redis-volume:
  vr-pharmacy-server-postgres-database-volume:
  vr-pharmacy-server-postgres-home-volume:

services:
  redis:
    image: redislabs/rejson:2.2.0
    container_name: vr-pharmacy-server-redis
    restart: always
    ports: ["6376:6379"]
    volumes:
      - vr-pharmacy-server-redis-volume:/data
    networks:
      - vr-pharmacy-server-databases-network

  postgres:
    image: postgres:12.9-alpine
    container_name: vr-pharmacy-server-postgres
    restart: always
    ports: ["5433:5432"]
    environment:
      POSTGRES_DB: vr-pharmacy-server
      POSTGRES_USER: vr-pharmacy-server
      POSTGRES_PASSWORD: vr-pharmacy-server
    volumes:
      - vr-pharmacy-server-postgres-database-volume:/var/lib/postgresql/data
      - vr-pharmacy-server-postgres-home-volume:/root
    networks:
      - vr-pharmacy-server-databases-network
